data = read.csv("WHO-COVID-19-global-data.csv")
View(data)
names(data)
table(data$New_cases , data$New_deaths)
View(table(data$New_cases , data$New_deaths))
select = select(data , Date_reported , Country , New_cases , New_deaths)
filter = filter(select , Country == "India")
plot(filter)
cov(filter$New_cases , filter$New_deaths)
cor(filter$New_cases , filter$New_deaths)
summary(filter)
pie(table(filter$New_cases))
pie(table(filter$New_deaths))
plot(x = filter$New_cases , y = rep(0,nrow(filter)))
boxplot(x = filter$New_cases , xlab = "New case" , horizontal = TRUE)
boxplot(x = filter$New_cases , xlab = "New case" , horizontal = TRUE , col = "red")
hist(filter$New_cases)
hist(filter$New_deaths)
plot(density(filter$New_cases))
plot(density(filter$New_deaths))
plot(x = filter$New_cases , y = filter$New_deaths , col = c("red" , "green"))
points(x = filter$New_cases , y = rep(-0.005 , nrow(filter)))
spineplot(x = filter$New_cases , y = filter$New_deaths)
mosaicplot(x = table(filter$New_cases ,filter$New_deaths) , las  = 3 )
plot(x = table(filter$New_cases) , type = "l")
plot(x = table(filter$New_cases) , type = "p")
plot(x = table(filter$New_cases) , type = "o")
plot(x = table(filter$New_cases) , type = "h")
plot(x = table(filter$New_cases) , type = "s")
barplot(tapply(filter$New_cases , filter$New_deaths , mean) , las = 3 )
plot(x = filter$New_cases , main = "Cases" , xlab = "value" , ylab="Case",pch=3)
unique(filter)
plot(filter)
plot(x = filter$New_cases , y = filter$New_deaths , col = c("red","green"))
x = filter$New_cases
y = filter$New_deaths
model = lm(y~x)
lines(x = filter$New_cases , y = model$fitted , col = "violet" , lwd = 3)
summary(model)
predict(object = model , newdata = data.frame(x = c(2,5,7)))
install.packages("coronavirus")
library(coronavirus)
plot(x = filter , col = as.integer(coronavirus$population))
plot(x = filter , col = as.numeric(coronavirus$population))
plot(x = filter$New_cases , y = filter$New_deaths , col = as.numeric(coronavirus$population) , pch = 3)
plot(x = filter$New_cases , y = filter$New_deaths ,  pch = 2 , lwd = 2 , col = "green")